README.md

Hi, I've tested how it works with YugabyteDB (an Open Source, PostgreSQL compatible Distributed SQL which uses a fork of PostgreSQL for the query layer to provide the same features, behavior, catalog views, aso) and it works so would be good to add it in the README
For information, here is the docker compose I used to test:
```
services:
web:
image: lovasoa/sqlpage
ports:
- "8080:8080"
volumes:
- .:/var/www
depends_on:
- db
environment:
DATABASE_URL: postgres://root:secret@db:5433/sqlpage
db: # The DB environment variable can be set to "mariadb" or "postgres" to test the code with different databases
ports:
- "5433:5433"
- "15433:15433"
image: yugabytedb/yugabyte
command: yugabyted start --background=false
environment:
YSQL_USER: root
YSQL_DB: sqlpage
YSQL_PASSWORD: secret
```

Add YugabyteDB (Open Source, PostgreSQL compatible Distributed SQL)

---

sqlpage/templates/shell.handlebars

The shell template was using a "target" attribute on the search <form> element, instead of an "action" attribute. The SQL script responsible for the search should be specified in an "action" attribute, otherwise the search does not work.

Fix broken search in shell template

---

src/webserver/http.rs

Since 0.10.0 ErrorWithStatus show as html error rendering.
This leads to breaking Basic Auth mechanism for instance.
The fix considers every ErrorWithStatus must not show details as html.

Fix ErrorWithStatus bubbling

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/user-authentication/protected_page.sql
examples/user-authentication/sqlpage/migrations/0000_init.sql
sqlpage/apexcharts.js
sqlpage/tabler-icons.svg
src/webserver/database/execute_queries.rs
tests/sql_test_files/it_works_set_variable_to_null.sql

- update dependencies
- Add support for resetting variables to a `NULL` value using `SET`. Previously, storing `NULL` in a variable would store the string `'null'` instead of the `NULL` value.

null variables

---

CHANGELOG.md
examples/official-site/sqlpage/migrations/28_tracking_component.sql
examples/official-site/sqlpage/migrations/29_divider_component.sql
sqlpage/templates/divider.handlebars
sqlpage/templates/tracking.handlebars

Implementation of the tracking component (https://tabler.io/docs/components/tracking)

Add tracking component

---

examples/official-site/sqlpage/migrations/30_breadcrumb_component.sql
sqlpage/templates/breadcrumb.handlebars

Breadcrumb component

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/table.handlebars

Add new visual table attributes

Table improvements

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/form.handlebars

A unique identifier for the input, which can then be used to select and manage the field with Javascript code. Usefull for advanced using as setting client side event listeners, interactive control of input field (disabled, visibility, read only, e.g.) and AJAX requests.

Form improvement : A unique identifier for the input fields

---

sqlpage/templates/button.handlebars

{{#if after_icon}}: This new block checks if the after_icon parameter is provided. If it is, it renders the icon after the text. In this way, the template will support both an icon before and after the text, depending on which parameters (icon or after_icon) are provided.

Update button.handlebars adding after-icon

---

CHANGELOG.md
src/webserver/database/execute_queries.rs
src/webserver/database/mod.rs
src/webserver/database/sqlpage_functions/function_definition_macro.rs
src/webserver/database/sqlpage_functions/functions.rs
src/webserver/database/syntax_tree.rs
src/webserver/http.rs
tests/index.rs
tests/select_temp_t.sql
tests/sql_test_files/README.md
tests/sql_test_files/it_works_temp_table_accessible_in_run_sql.sql
tests/sql_test_files/it_works_temp_table_accessible_in_run_sql_nomssql.sql

see https://github.com/lovasoa/SQLpage/issues/338

 faster run_sql with shared database connection

---

examples/official-site/sqlpage/migrations/23_uploaded_file_functions.sql
src/webserver/database/sqlpage_functions/functions.rs
tests/index.rs
tests/uploaded_file_name_test.sql

Closes #333 
Tested with
```sql
SET fname = sqlpage.uploaded_file_name('f');
SELECT 'debug' AS component;
SELECT $fname AS fname;
SELECT 'form' AS component, 'post' AS method;
SELECT 'file' AS type, 'f' AS name, '' AS label;
```
Documentation tbd

add uploaded_file_name function

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/csv.handlebars

Hi,
I've added a CSV button size top-level parameter to the csv.handlebars & updated the documentation - copied button size parameter description and pasted it into the CSV button size description. This is my first pull request. Please feel free to tell me if you need anything more to be fulfilled before making a pull request.

Added CSV button size top-level parameter

---

examples/official-site/sqlpage/migrations/25_read_file_as_text.sql

"text" property is specified instead of "contents_md"

Code mistake in 25_read_file_as_text.sql

---

sqlpage/templates/shell.handlebars

Adds semantic classes, ids, and tag names
Should give us more semantic CSS styling control. Example, `body` element theming, [à la Shoelace](https://shoelace.style/getting-started/themes):
```sql
select 'shell' as component,
'sl-theme-dark' as body_class,
[...]
```
- - -
⚠️ The new `<footer>` and `<header>` tags may break styling that relied on css selections such as `body > div:last-of-type {...}` prior to semantic tagging.

adds semantic classes, ids, and tags

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/table.handlebars

The "table" component template will now set the width property of the table component div to "fit-content" if the table defines a boolean "overflow" attribute set to TRUE.
This feature is useful for "wide" tables, as it prevents columns clipping on the right, enabling horizontal scrolling via the browser scrollbar.

Added "overflow" attribute to the "table" component

---

examples/official-site/sqlpage/migrations/18_button.sql
sqlpage/templates/button.handlebars

Sets .btn-icon class, which trims horizontal padding.
See https://tabler.io/docs/components/buttons#icon-buttons

Added "narrow" attribute to the "button" component

---

examples/official-site/examples/dynamic_menu.sql
examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/shell.handlebars

Use parse_json helper to enable the use of the object form of "shell" with JSON containing menu items. Also in this pull request is an explicit filter on blank items (for example, generated via `NULL AS menu_item` or via `'' AS menu_item`). The latter feature simplifier creation of dynamic menus based on certain conditions, such as whether the user is authenticated or not. 
Note, however, `'' AS menu_item` presently fails due to parse_json and should not be used. `'{}' AS menu-item` apparently works fine.

Parse JSON menu_item for SQLite and skip blank items

---

sqlpage/templates/map.handlebars

The points that are shown on the map are filtered on {{~if latitude}}. By adding "inculdeZero=true" the points that have a latitude of 0 will also be shown.

Do not ignore points with a latitude of 0 in map.handlebars

---

examples/official-site/examples/handle_enctype.sql
examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/form.handlebars

#458 - allow user to set formenctype

---

CHANGELOG.md
Dockerfile
examples/CRUD - Authentication/README.md
examples/CRUD - Authentication/www/create_session.sql
examples/charts, computations and custom components/index.sql
examples/charts, computations and custom components/taptempo.sql
examples/corporate-conundrum/New Game.sql
examples/corporate-conundrum/game.sql
examples/corporate-conundrum/next-question.sql
examples/corporate-conundrum/question.sql
examples/corporate-conundrum/wait.sql
examples/official-site/blog.sql
examples/official-site/sqlpage/migrations/47_link.sql
lambda.Dockerfile
src/webserver/database/sql.rs
src/webserver/database/sqlpage_functions/functions.rs
src/webserver/database/sqlpage_functions/mod.rs
src/webserver/database/sqlpage_functions/url_parameter_deserializer.rs
src/webserver/database/syntax_tree.rs
tests/sql_test_files/it_works_link.sql
tests/sql_test_files/it_works_query_string.sql
tests/sql_test_files/it_works_run_sql_from_database.sql

sqlpage.link('test.sql', '{"x":1}') = 'test.sql?x=1'

new sqlpage.link function

---

tests/index.rs

This patch disable the use of system CA root.
fix https://github.com/lovasoa/SQLpage/issues/541

Disable CA host certificat on test.

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/shell.handlebars

Change the "theme" property of sidebar as "sidebar_theme" (#540) and accept it as parameter and not a boolean.
I don't really know "where" to place the documentation, as the folder docs doesn't include the documentation.sql of the components nor the Markdown files with docs.

Change the sidebar theme as "sidebar_theme"

---

examples/handle-404/api/404.sql
examples/handle-404/api/index.sql
examples/handle-404/index.sql
src/webserver/http.rs
tests/404.sql
tests/index.rs

Fixes #529 .
@lovasoa Is this an acceptable business logic to you? I'm sure the code can be cleaned up, and there might be an argument for using `PathBuf` directly instead of doing `String` manipulation, but besides that?

feat: add 404.sql handler

---

Cargo.lock
Cargo.toml
src/app_config.rs
src/main.rs

Following the [discussion](https://github.com/lovasoa/SQLpage/discussions/562) about getting SQLpage version information from the command line, I used the [clap](https://github.com/clap-rs/clap) library to provide basic CLI parsing.
As a Go programmer, I looked for an equivalent to Go _cobra_ and _clap_ looked like a good match.
Now both `sqlpage --help` and `sqlpage --version` work.
This is my first attempt at rust ever, so I don't fully understand what I did, in particular the use of `async fn main()` instead of `fn main()` in main.rs. Please review carefully.
I basically followed [one of the examples](https://github.com/clap-rs/clap/blob/v3.1.18/examples/tutorial_derive/04_02_parse.rs) provided by _clap_.

Command line parsing to get version information

---

sqlpage/templates/form.handlebars

I noticed that textarea form components and select form components would ignore my class attribute assignments. This PR fixes that template. 
How to use:
```
select 'form' as component;
-- should have a big margin below and a padding
select
'select' as type,
'Test Label' as label,
'mb-4 p-3' as class,
'[{"label":"Test Label","value":"test"}]' as options;
-- put a field here just to see that the margin worked
select 'test' as name;
-- should have a big margin above and a big margin below 
select 'textarea' as type, 'mb-4 mt-4' as class;
-- put another field here just to see that it worked
select 'test2' as name;
```

Fix textarea and select components ignoring class attribute

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/shell.handlebars

sample follows
```sql
select 
'shell'                     as component,
'SQLPage: SQL to web pages' as title,
'database'                  as icon,
'/'                         as link,  
JSON('{"title":"Community","submenu":[{"link":"//github.com/lovasoa/sqlpage/issues","title":"Report a bug","icon":"bug","target":"__blank"}]}') as menu_item,
JSON('{"title":"Report a bug","link":"//github.com/lovasoa/sqlpage/issues","target":"__blank"}') as menu_item,
'boxed'                     as layout,
'en-US'                     as language,
'Go from SQL queries to web applications in an instant.' as description,
'https://sql.datapage.app/sqlpage_social_preview.webp' as preview_image,
'Poppins'                   as font,
'https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11/build/highlight.min.js' …
```

feat: open a new tab when clicking on the menu and submenu.

---

CHANGELOG.md
examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/form.handlebars

add `empty_option` to the form component

---

src/app_config.rs
src/file_cache.rs
src/filesystem.rs
src/webserver/http.rs
src/webserver/mod.rs
src/webserver/routing.rs

replaces https://github.com/sqlpage/SQLPage/pull/786

Handle requests without file extension

---

CHANGELOG.md
examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/sqlpage.js
sqlpage/templates/table.handlebars
tests/end-to-end/official-site.spec.ts
tests/end-to-end/package-lock.json

Related to #802
This is the best I could hack, with my limited knowledge and in the time I had to spare. The basic usage is as follows:
- to select which columns should have their numbers formatted according to user locale, you specify them just like you would do for markdown
- there is an extra option that allows you to choose the exact number of decimal digits to be used when formatting, if you need such a precision. This is used for the entire table.
E.G: if you need a table with two columns with numbers formatted using exactly three decimals, and a markdown column with links, you would write
```
select 'table' as component,
'links'  as markdown,
'col A' as number_format_locale,
'col B' as number_format_locale,
3 as number_format_digits,
TRUE as sort;
```
**Pros:**
- The changes are …

Added an option to format numbers using `toLocaleString()` for table columns

---

CHANGELOG.md
src/webserver/database/mod.rs
src/webserver/database/sql.rs
tests/sql_test_files/it_works_case_variables.sql

fix https://github.com/sqlpage/SQLPage/issues/818
- **use numbered parameters in sqlite**
- **implement parameter deduplication**
- **implement parameter re-duplication for mysql**

fix parameter binding order

---

examples/official-site/your-first-sql-website/index.sql

For the issue #782.
@lovasoa Feel free to customize it.
At least you have a template.
I used tag_name for the JSON, but name would also work.

Insert the newest sqlpage version

---

CHANGELOG.md
sqlpage/templates/shell.handlebars

By default handlebars handles all falsy values in the same way. This means that there is no way to easily remove the footer from the shell component, because no matter if you leave it empty or give it a `false` value, the default "Built with SQLPage" one appears.
With this small change, setting the value of the `footer` parameter to the empty string will completely hide the footer. As an example, this is the configuration from the `shell.json` in my project:
```
{
"component": "shell",
"footer": "",
"title": "AA BB CC",
"javascript": "/scripts/htmx.min.js",
"link": "/",
"menu_item": [
{"link": "p1", "title": "Page 1"},
{"link": "p2", "title": "Page 2"}
]
}
```

Option to completely hide the footer from the shell.handlebars template

---

sqlpage/sqlpage.json

With the actual sqlpage.json file, if you start SQLPage without knowing or noticing the connection string, an error appears:
[2025-03-17T10:58:01.236Z WARN  sqlpage::webserver::database::connect] Failed to connect to the database: error returned from database: (code: 14) unable to open database file. Retrying in 5 seconds.  
Because the specified path.

Revert sqlpage.json

---

CHANGELOG.md
examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/sqlpage.css
sqlpage/sqlpage.js
sqlpage/templates/table.handlebars

As per issue #860 this pull request implements two new parameters for the table component: `first_row_is_footer` and `freeze_footers`

Added an option to create footers in the table component 

---

examples/official-site/extensions-to-sql.md
examples/official-site/extensions-to-sql.sql
examples/official-site/sqlpage/migrations/01_documentation.sql

Closes #877
I'm quite happy with this addition! I hope it'll save some time to newcomers.
However, I'm not convinced that the page belongs in 'Your first SQL website' directory.
Would you agree to move it up?
Documenting already took quite some time, and I don't have much energy to update this PR if you have suggestions.
So don't hesitate to rephrase and rework things if you don't like them!

Documentation: add "Extensions to SQL" page

---

examples/official-site/sqlpage/migrations/01_documentation.sql
sqlpage/templates/shell.handlebars

Allows the user to have SQL that indicates that a navigation bar should be shown as "active" in the shell.
```sql
select
'shell' as component
, '{"title": "Example Menu Item 1", "active": true}' as menu_item
, '{"title": "Example Menu Item 2"}' as menu_item
```
Also works in the sidebar:
```sql
select
'shell' as component
, true as sidebar
, '{"title": "Example Menu Item 1", "active": true}' as menu_item
, '{"title": "Example Menu Item 2"}' as menu_item
```

Add active indicator to the shell nav items

---

src/webserver/database/sqlpage_functions/url_parameter_deserializer.rs

Fix #879
Not quite sure of what I'm doing, as I'm discovering the codebase

Remove url-encoded surrounding quotes to URL parameters

---

.github/workflows/release.yml

fixes https://github.com/sqlpage/SQLPage/issues/925
fixes https://github.com/sqlpage/SQLPage/issues/709

linux builds with old glibc

---

.cargo/config.toml
tests/sql_test_files/it_works_sqrt.sql

Closes #937
I think this is the easy way of setting the env var.
If we want to make this optional it could be implemented via features, but IMO making it optional would be overkill.

Added a compile time flag to compile SQLite with builtin math functions

---

sqlpage/migrations/README.md
src/app_config.rs
src/main.rs

This update adds a command line interface to create migrations directly with sqlpage, and have it manage the timestamps and uniqueness of migration names.
This is an implementation in rust of #915 that I had previously implemented as a separate system written in nodejs.
You can run "sqlpage create-migration example_migration_1" or "sqlpage create-migration "My Test Migration"" for instance, and it will create a migration under sqlpage/migrations with the filename [timestamp]_example_migration_1.sql or [timestamp]_my_test_migration.sql.
The code handles special characters, and collisions in migration names.

Added create-migration command line instruction
